version: '3.7'

services:
  rabbitmq1:
    image: rabbitmq:3.8-management
    container_name: rabbitmq1
    environment:
      - RABBITMQ_ERLANG_COOKIE=rDlMa6F69D9Jx9lZ5v4Gp7n9ZcT4QNb5
      - RABBITMQ_NODENAME=rabbit@rabbitmq1
      - NAME_NODE=rabbitmq1
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - ./config:/etc/rabbitmq

  rabbitmq2:
    image: rabbitmq:3.8-management
    container_name: rabbitmq2
    environment:
      - RABBITMQ_ERLANG_COOKIE=rDlMa6F69D9Jx9lZ5v4Gp7n9ZcT4QNb5
      - RABBITMQ_NODENAME=rabbit@rabbitmq2
      - NAME_NODE=rabbitmq2
    ports:
      - "5673:5672"
      - "15673:15672"
    volumes:
      - ./config:/etc/rabbitmq
    depends_on:
      - rabbitmq1

  rabbitmq3:
    image: rabbitmq:3.8-management
    container_name: rabbitmq3
    hostname: rabbitmq3
    environment:
      - RABBITMQ_ERLANG_COOKIE=rDlMa6F69D9Jx9lZ5v4Gp7n9ZcT4QNb5
      - RABBITMQ_NODENAME=rabbit@rabbitmq3
      - NAME_NODE=rabbitmq3
    ports:
      - "5674:5672"
      - "15674:15672"
    volumes:
      - ./config:/etc/rabbitmq
    depends_on:
      - rabbitmq1
