version: '3.7'

services:
  rabbitmq1:
    image: my-rabbitmq-cluster
    container_name: rabbitmq1
    hostname: rabbitmq1
    environment:
      - RABBITMQ_ERLANG_COOKIE=uniquecookie
      - RABBITMQ_NODENAME=rabbit@rabbitmq1
    ports:
      - "5672:5672"
      - "15672:15672"
    extra_hosts:
      - "rabbitmq2:172.17.0.3"  # Adiciona hostname e IP do rabbitmq2
      - "rabbitmq3:172.17.0.4"  # Adiciona hostname e IP do rabbitmq3

  rabbitmq2:
    image: my-rabbitmq-cluster
    container_name: rabbitmq2
    hostname: rabbitmq2
    environment:
      - RABBITMQ_ERLANG_COOKIE=uniquecookie
      - RABBITMQ_NODENAME=rabbit@rabbitmq2
    ports:
      - "5673:5672"
      - "15673:15672"
    extra_hosts:
      - "rabbitmq1:172.17.0.2"  # Adiciona hostname e IP do rabbitmq1
      - "rabbitmq3:172.17.0.4"  # Adiciona hostname e IP do rabbitmq3
    depends_on:
      - rabbitmq1

  rabbitmq3:
    image: my-rabbitmq-cluster
    container_name: rabbitmq3
    hostname: rabbitmq3
    environment:
      - RABBITMQ_ERLANG_COOKIE=uniquecookie
      - RABBITMQ_NODENAME=rabbit@rabbitmq3
    ports:
      - "5674:5672"
      - "15674:15672"
    extra_hosts:
      - "rabbitmq1:172.17.0.2"  # Adiciona hostname e IP do rabbitmq1
      - "rabbitmq2:172.17.0.3"  # Adiciona hostname e IP do rabbitmq2
    depends_on:
      - rabbitmq1


