version: '3.7'

services:
  rabbitmq1:
    image: rabbitmq:3.8-management
    ports:
      - "5673:5672"
      - "15673:15672"
    environment:
      - RABBITMQ_ERLANG_COOKIE=rDlMa6F69D9Jx9lZ5v4Gp7n9ZcT4QNb5
      - RABBITMQ_NODENAME=rabbit@rabbitmq1
      - HOST_NAME_NODE=rabbitmq1
    volumes:
      - "./scripts:/scripts" # Mapeando o diretório local para dentro do contêiner
    command: /bin/bash -c "/scripts/start_rabbitmq.sh" 

  rabbitmq2:
    image: rabbitmq:3.8-management
    ports:
      - "5674:5672"
      - "15674:15672"
    environment:
      - RABBITMQ_ERLANG_COOKIE=rDlMa6F69D9Jx9lZ5v4Gp7n9ZcT4QNb5
      - RABBITMQ_NODENAME=rabbit@rabbitmq2
      - HOST_NAME_NODE=rabbitmq2
    volumes:
      - "./scripts:/scripts" # Mapeando o diretório local para dentro do contêiner
    command: /bin/bash -c "/scripts/start_rabbitmq.sh" 

  rabbitmq3:
    image: rabbitmq:3.8-management
    ports:
      - "5675:5672"
      - "15675:15672"
    environment:
      - RABBITMQ_ERLANG_COOKIE=rDlMa6F69D9Jx9lZ5v4Gp7n9ZcT4QNb5
      - RABBITMQ_NODENAME=rabbit@rabbitmq3
      - HOST_NAME_NODE=rabbitmq3
    volumes:
      - "./scripts:/scripts" # Mapeando o diretório local para dentro do contêiner
    command: /bin/bash -c "/scripts/start_rabbitmq.sh" 

